<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160111120406 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE typo3_flow_security_account CHANGE failedauthenticationcount failedauthenticationcount INT DEFAULT NULL");
		$this->addSql("ALTER TABLE typo3_media_domain_model_thumbnail DROP FOREIGN KEY FK_B7CE141455FF4171");
		$this->addSql("ALTER TABLE typo3_media_domain_model_thumbnail CHANGE configuration configuration LONGTEXT NOT NULL COMMENT '(DC2Type:flow_json_array)'");
		$this->addSql("DROP INDEX originalasset_configurationhash ON typo3_media_domain_model_thumbnail");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_B7CE141455FF41717F7CBA1A ON typo3_media_domain_model_thumbnail (originalasset, configurationhash)");
		$this->addSql("ALTER TABLE typo3_media_domain_model_thumbnail ADD CONSTRAINT FK_B7CE141455FF4171 FOREIGN KEY (originalasset) REFERENCES typo3_media_domain_model_asset (persistence_object_identifier)");
		$this->addSql("DROP INDEX documentnodeidentifier ON typo3_neos_eventlog_domain_model_event");
		$this->addSql("ALTER TABLE typo3_neos_eventlog_domain_model_event CHANGE data data LONGTEXT NOT NULL COMMENT '(DC2Type:flow_json_array)'");
		$this->addSql("ALTER TABLE typo3_typo3cr_domain_model_nodedata CHANGE accessroles accessroles LONGTEXT NOT NULL COMMENT '(DC2Type:flow_json_array)', CHANGE dimensionvalues dimensionvalues LONGTEXT NOT NULL COMMENT '(DC2Type:flow_json_array)'");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE typo3_flow_security_account CHANGE failedauthenticationcount failedauthenticationcount INT DEFAULT 0");
		$this->addSql("ALTER TABLE typo3_media_domain_model_thumbnail DROP FOREIGN KEY FK_B7CE141455FF4171");
		$this->addSql("ALTER TABLE typo3_media_domain_model_thumbnail CHANGE configuration configuration LONGTEXT NOT NULL COLLATE utf8_unicode_ci COMMENT '(DC2Type:json_array)'");
		$this->addSql("DROP INDEX uniq_b7ce141455ff41717f7cba1a ON typo3_media_domain_model_thumbnail");
		$this->addSql("CREATE UNIQUE INDEX originalasset_configurationhash ON typo3_media_domain_model_thumbnail (originalasset, configurationhash)");
		$this->addSql("ALTER TABLE typo3_media_domain_model_thumbnail ADD CONSTRAINT FK_B7CE141455FF4171 FOREIGN KEY (originalasset) REFERENCES typo3_media_domain_model_asset (persistence_object_identifier)");
		$this->addSql("ALTER TABLE typo3_neos_eventlog_domain_model_event CHANGE data data LONGTEXT NOT NULL COLLATE utf8_unicode_ci COMMENT '(DC2Type:array)'");
		$this->addSql("CREATE INDEX documentnodeidentifier ON typo3_neos_eventlog_domain_model_event (documentnodeidentifier)");
		$this->addSql("ALTER TABLE typo3_typo3cr_domain_model_nodedata CHANGE dimensionvalues dimensionvalues LONGTEXT NOT NULL COLLATE utf8_unicode_ci COMMENT '(DC2Type:json_array)', CHANGE accessroles accessroles LONGTEXT NOT NULL COLLATE utf8_unicode_ci COMMENT '(DC2Type:json_array)'");
	}
}